-- Modern Lab V2 Supabase schema
-- Run this in Supabase SQL Editor before using the app.
-- Chinese category names use PostgreSQL Unicode escapes to avoid copy/paste encoding issues:
-- U&'\4EA4\63A5' = 交接, U&'\5099\5FD8' = 備忘, U&'\5F85\8FA6' = 待辦

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  role text not null default 'staff' check (role in ('admin', 'staff')),
  account_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists display_name text;
alter table public.profiles add column if not exists role text not null default 'staff';
alter table public.profiles add column if not exists account_id text;
alter table public.profiles add column if not exists created_at timestamptz not null default now();
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

alter table public.categories add column if not exists name text;
alter table public.categories add column if not exists created_at timestamptz not null default now();

insert into public.categories (name)
values
  (U&'\4EA4\63A5'),
  (U&'\5099\5FD8'),
  (U&'\5F85\8FA6'),
  (U&'\6536\6AA2'),
  (U&'\8017\6750'),
  (U&'\5176\4ED6')
on conflict (name) do nothing;

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  content text not null,
  category_name text not null default U&'\5F85\8FA6',
  priority boolean not null default false,
  deadline timestamptz,
  status int not null default 0,
  creator_id uuid references public.profiles(id) on delete set null,
  history jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tasks add column if not exists content text;
alter table public.tasks add column if not exists workflow text not null default 'general';
alter table public.tasks add column if not exists category_name text not null default U&'\5F85\8FA6';
alter table public.tasks add column if not exists clinic text;
alter table public.tasks add column if not exists category text;
alter table public.tasks add column if not exists priority boolean not null default false;
alter table public.tasks add column if not exists deadline timestamptz;
alter table public.tasks add column if not exists status int not null default 0;
alter table public.tasks add column if not exists creator_id uuid references public.profiles(id) on delete set null;
alter table public.tasks add column if not exists creator_name text;
alter table public.tasks add column if not exists picker text;
alter table public.tasks add column if not exists claimed_at timestamptz;
alter table public.tasks add column if not exists completed_at timestamptz;
alter table public.tasks add column if not exists is_stocked boolean not null default false;
alter table public.tasks add column if not exists stocker text;
alter table public.tasks add column if not exists stocked_at timestamptz;
alter table public.tasks add column if not exists image_urls jsonb not null default '[]'::jsonb;
alter table public.tasks add column if not exists checklist jsonb not null default '[]'::jsonb;
alter table public.tasks add column if not exists history jsonb not null default '[]'::jsonb;
alter table public.tasks add column if not exists created_at timestamptz not null default now();
alter table public.tasks add column if not exists updated_at timestamptz not null default now();

create index if not exists tasks_status_idx on public.tasks(status);
create index if not exists tasks_category_name_idx on public.tasks(category_name);
create index if not exists tasks_created_at_idx on public.tasks(created_at desc);

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.tasks enable row level security;

drop policy if exists "profiles readable by signed in users" on public.profiles;
create policy "profiles readable by signed in users"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "profiles self update" on public.profiles;
create policy "profiles self update"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "categories readable by signed in users" on public.categories;
create policy "categories readable by signed in users"
on public.categories for select
to authenticated
using (true);

drop policy if exists "tasks readable by signed in users" on public.tasks;
create policy "tasks readable by signed in users"
on public.tasks for select
to authenticated
using (true);

drop policy if exists "tasks insertable by signed in users" on public.tasks;
create policy "tasks insertable by signed in users"
on public.tasks for insert
to authenticated
with check (auth.uid() = creator_id);

drop policy if exists "tasks updateable by signed in users" on public.tasks;
create policy "tasks updateable by signed in users"
on public.tasks for update
to authenticated
using (true)
with check (true);
